cal/urls.py
from django.conf.urls import patterns, url, include	
from django.contrib import admin
from cal import views

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', views.render_first_look_calendar, name='render_first_look_calendar'),
	url(r'^entry_not_avail/', views.render_second_look_calendar, name='render_second_look_calendar'),
	url(r'^(?P<entry_id>\d+)/$', views.process_cal, name='process_cal'),

    )

dormserv/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
	url(r'^$', include('home.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls')),
    url(r'^cal/', include('cal.urls')),
    url(r'^menu/', include('menu.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^checkout/', include('checkout.urls')),
    url(r'^profile/', include('userprofile.urls')),
    url(r'^kitchen/', include('kitchen.urls')),
    url(r'^driver/', include('drivers.urls')),
    url(r'^refer/', include('promotion.urls')),

)

if not settings.DEBUG:
   urlpatterns += patterns('',
       (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
   )

users/urls.py
from django.conf.urls import patterns, url, include	
from django.contrib import admin
from users import views

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^login', views.user_login, name='user_login'),
    url(r'^register', views.user_reg, name='user_reg'),
    url(r'^process_new_user', views.process_new_user, name='process_new_user'),
    url(r'^logout', views.user_logout, name='user_logout'),
    url(r'^homemenu', views.homemenu, name='homemenu'),
    url(r'^faq', views.faq, name='faq'),
    )

users/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date, time, timedelta
from googlemaps import GoogleMaps
from restaurants.models import Restaurant
from django.conf import settings

class UserProfile(models.Model):
	# Basic profile data for UserProfile object
	user = models.OneToOneField(User)
	address = models.CharField(max_length=50)
	city = models.CharField(max_length=50)
	state = models.CharField(max_length=30, choices=settings.US_STATES)
	phone = models.CharField(max_length=12)

	# Restaurant this UserProfile is mapped to
	restaurant = models.ForeignKey(Restaurant)

	def phone_just_digits(self):
		digits = ""
		for k in range(len(self.phone)):
			if phone[k] == ('1' or '2' or '3' or '4' or '5' or '6' or '7' or '8' or '9' or '0'):
				digits = digits + phone[k]

		return digits

	def get_address_string(self):
		space = " "
		address = str(self.address)
		city = str(self.city)
		state = str(self.state)
		return address + space + city + space + state

	def dist_to_restaurant(self):
		api_key = settings.GOOGLE_MAPS
		gmaps = GoogleMaps(api_key)
		start = self.get_address_string
		stop = self.restaurant.get_address_string
		dirs = gmaps.directions(start, stop)
		dist = dirs['Directions']['Distance']['meters']
		dist_in_miles = float(dist*.000621371)
		return dist_in_miles

	def time_to_user_profile(self):
		api_key = settings.GOOGLE_MAPS
		gmaps = GoogleMaps(api_key)
		start = self.get_address_string
		stop = self.restaurant.get_address_string
		dirs = gmaps.directions(start, stop)
		time = dirs['Directions']['Duration']['seconds']
		return time

	def dist_to_restaurant_string(self):
		return str(self.dist_to_restaurant)

	def time_to_user_profile_string(self):
		time = self.time_to_user_profile
		mins = str(time/60)
		secs = str(time%60)
		return mins + ":" + secs

	def __unicode__(self):
		return self.user.username

class DriverProfile(models.Model):
	# Basic profile data for DriverProfile object
	user = models.OneToOneField(User)
	address = models.CharField(max_length=50)
	city = models.CharField(max_length=50)
	state = models.CharField(max_length=2, choices=settings.US_STATES)
	phone = models.CharField(max_length=12)

	# Restaurant this DriverProfile is mapped to
	restaurant = models.ForeignKey(Restaurant)

	def __unicode__(self):
		return self.user.username

class StaffProfile(models.Model):
	# Basic profile data for StaffProfile object
	user = models.OneToOneField(User)
	address = models.CharField(max_length=50)
	city = models.CharField(max_length=50)
	state = models.CharField(max_length=2, choices=settings.US_STATES)
	phone = models.CharField(max_length=12)

	# Restaurant this StaffProfile is mapped to
	restaurant = models.ForeignKey(Restaurant)

	def __unicode__(self):
		return self.user.username

users/views.py
import re
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
from django.conf import settings
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from users.models import UserProfile, DriverProfile, StaffProfile
from restaurants.models import Restaurant
from demand.models import Demand

from pygeocoder import Geocoder
from googlemaps import GoogleMaps

def user_reg(request):
	context = RequestContext(request)

	states = []

	for state in settings.US_STATES:
		states.append(state[1])

	return render_to_response(
		'register.html',
		{
		'states':states,
		},
		context)

def process_new_user(request):
	context = RequestContext(request)

	if request.method == 'POST':
		first = request.POST.get('first')
		last = request.POST.get('last')
		username = request.POST.get('username')
		password1 = request.POST.get('password1')
		password2 = request.POST.get('password2')
		address1 = request.POST.get('address1')
		address2 = request.POST.get('address2')
		city = request.POST.get('city')
		state = request.POST.get('state')
		phone = request.POST.get('phone')

		address_string = get_address_string(address1, address2, city, state)

		un = verify_username(username)
		pw = verify_password(password1, password2)
		addr = verify_address(address_string)
		num = verify_phone(phone)
		nom = verify_name(first, last)
		res = verify_restaurant(address_string)

		if un[0] and pw[0] and addr[0] and num[0] and nom[0] and res[0]:
			success = store_user_data(un, pw, addr, address2, num, nom, res, request)
			return success

		else:
			failure = gather_errors_for_template(first, last, username, address_string, phone, 
				un, pw, addr, num, nom, res, request)
			return failure
	
	return user_reg(request)

def get_profile_type(user):
	'''
	Input: a User object
	Output:	1 if this is a UserProfile
			2 if this is a DriverProfile
			3 if this is a StaffProfile
			0 if it is not any type of profile
	'''

	for up in UserProfile.objects.all():
		if up.user == user:
			return 1

	for dp in DriverProfile.objects.all():
		if dp.user == user:
			return 2

	for sp in StaffProfile.objects.all():
		if sp.user == user:
			return 3

	return 0

def return_associated_profile_type(user):
	'''
	Input: a User object
	Output:	1 if this is a UserProfile
			2 if this is a DriverProfile
			3 if this is a StaffProfile
			0 if it is not any type of profile
	'''

	for up in UserProfile.objects.all():
		if up.user == user:
			return up

	for dp in DriverProfile.objects.all():
		if dp.user == user:
			return dp

	for sp in StaffProfile.objects.all():
		if sp.user == user:
			return sp

	return None

def user_login(request):
	context = RequestContext(request)
	user = request.user

	ptype = get_profile_type(user)

	if user.is_superuser:
		return redirect('/admin')

	if user.is_active:
		if ptype == 1:
			return redirect('/cal')
		if ptype == 2:
			return redirect('/driver')
		if ptype == 3:
			return redirect('/kitchen')

	if request.method == 'POST':
		un = request.POST['username']
		pw = request.POST['password']

		user = authenticate(username=un, password=pw)

		if user is not None:
			if user.is_active:
				login(request, user)
				return user_type_redirect_manager(user, request)

			else:
				return render_to_response(
					'account_disabled.html',
					{},
					context)

		else:
			error = "We can't seem to find a user with those details. Try again!"
			return render_to_response(
				'login.html',
				{
				'error':error,
				},
				context)

	return render_to_response(
		'login.html',
		{},
		context)

@login_required
def user_logout(request):
	logout(request)

	return redirect("/users/login")

def user_type_redirect_manager(user, request):
	context = RequestContext(request)

	ptype = get_profile_type(user)
	print ptype

	if user.is_active:
		if ptype == 1:
			return redirect('/cal/')
		if ptype == 2:
			return redirect('/driver')
		if ptype == 3:
			return redirect('/kitchen')

	return redirect('user_login')

def gather_errors_for_template(first, last, username, address_string, phone,
	un, pw, addr, num, nom, res, request):
	context = RequestContext(request)

	un_errors = []
	pw_errors = []
	addr_errors = []
	num_errors = []
	nom_errors = []
	res_errors = []

	if not un[0]:
		un_errors.append(un[1])

	if not pw[0]:
		pw_errors.append(pw[1])

	if not addr[0]:
		addr_errors.append(addr[1])
 
	if not num[0]:
		num_errors.append(num[1])

	verification = verify_address(address_string)

	if verification[1] == "Unfortunately, we are not yet delivering to these addresses.":
		demand = demand_instance_found(first, last, username, address_string, phone, request)
		return demand

	if not res[0] and verification[0]:
		if res[1] == "Please enter a valid address.":
			res_errors.append(res[1])
		else:
			demand = demand_instance_found(first, last, username, address_string, phone, request)
			return demand

	states = []

	for state in settings.US_STATES:
		states.append(state[1])

	return render_to_response(
		'register.html',
		{
		'un_errors':un_errors,
		'pw_errors':pw_errors,
		'addr_errors':addr_errors,
		'num_errors':num_errors,
		'res_errors':res_errors,
		'states':states,
		},
		context)

def demand_instance_found(first, last, username, address_string, phone, request):
	context = RequestContext(request)

	_demand = Demand(
		first=first,
		last=last,
		email=username,
		phone=phone,
		address=address_string
		)

	_demand.save()

	return render_to_response(
		"coming_soon.html",
		{},
		context)

def store_user_data(un, pw, addr, addr2, num, nom, res, request):
	context = RequestContext(request)

	username = un[1]
	password = pw[1]
	address = addr[1] + addr2
	city = addr[2]
	state = addr[3]
	phone = num[1]
	first = nom[1]
	last = nom[2]
	restaurant = res[1]

	_user = User(
		first_name=first,
		last_name=last,
		username=username)

	_user.set_password(password)

	_user.save()


	try:
		_user_profile = UserProfile(
			user=_user,
			address=address,
			city=city,
			state=state,
			phone=phone,
			restaurant=restaurant)
	except:
		_user.delete()
		
		return render_to_response(
			"error.html",
			{},
			context)

	_user_profile.save()

	new_user = authenticate(username=username,
		password=password)

	login(request, new_user)

	return redirect('/cal')

def verify_restaurant(start):
	api_key = settings.GOOGLE_MAPS
	geo = GoogleMaps(api_key)
	error = "Unfortunately, we are not yet delivering in your area."
	wrong_addr = False

	for r in Restaurant.objects.all():
		end = r.get_address_string()
		try:
			dirs = geo.directions(start, end)
		except:
			wrong_addr = True
			error = "Please enter a valid address."

		dist = float("inf")

		if not wrong_addr:
			dist = dirs['Directions']['Distance']['meters']

		good_radii = ['LaSalle', 'lasalle', 'laSalle', 'LaSalle', 'Lasalle', 'Morreene']

		start_split = start.split(" ")

		for radius in good_radii:
			if radius in start_split:
				return (True, r)

		if dist < r.max_radius:
			return (True, r)

	return (False, error)

def verify_name(first, last):
	if not (first > 0) and (last > 0):
		error = "You must provide both a first and last name."
		return (False, error)
	f = first.title()
	l = last.title()
	return (True, f, l)

def verify_phone(phone):
	if not re.match(r"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", phone):
		error = "Please provide a valid phone number."
		return (False, error)

	to_pass_back = ""

	print phone

	digits = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
	for digit in phone:
		print digit
		if digit in digits:
			to_pass_back = to_pass_back + digit

	print to_pass_back

	return (True, to_pass_back)

def verify_address(address_string):
	api_key = settings.GOOGLE_MAPS
	geo = GoogleMaps(api_key)

	components = address_string.split(" ")

	start = "902 Sedgefield Street, Durham, NC"

	try:
		directions = geo.directions(address_string, start)
	except:
		error = "Please enter a valid address."
		return (False, error)

	split = str(address_string).split(",")
	addr = split[0]
	city = split[1]
	state = split[2]
	return (True, addr, city, state)

def verify_password(password1, password2):
	if password1 != password2:
		error = "Passwords do not match."
		return (False, error)
	if len(password1) < 7:
		error = "Passwords must be at least 6 characters in length."
		return (False, error)

	return (True, password1)

def verify_username(username):
	if not re.match(r"^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$", username):
		error = "Please enter a valid email address."
		return (False, error)

	users = User.objects.all()
	for u in users:
		if u.username == username:
			error = "This email already has an account associated with it."
			return (False, error)

	return (True, username)

def get_address_string(address1, address2, city, state):
	space = " "
	comma = ", "
	#if len(address2) > 0:
	#	return address1 + space + address2 + comma + city + comma + state

	return address1 + comma + city + comma + state


def homemenu(request):
	context = RequestContext(request)

	return render_to_response(
		'homemenu.html',
		{},
		context)

def faq(request):
	context = RequestContext(request)

	return render_to_response(
		'faq.html',
		{},
		context)

users/templates/account_disabled.html
{% extends "base.html" %}

{% block heading %}

	<h1>Dormserv: Account Disabled</h1>

{% endblock %}

<h2>Oh no! It looks like your account is disabled.</h2>
<h3>Want to reconfigure your account? Contact us!</h3>

{% block content %}

{% endblock %}

users/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/overeasy.css' %}">
<link href='http://fonts.googleapis.com/css?family=Oswald|Abel' rel='stylesheet' type='text/css'>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Over Easy</title>

    <!-- Bootstrap -->

    <title>{% block title %}Over Easy{% endblock %}</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
        <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-56248193-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>
  <body background={% static "img/overeasy-background.jpeg" %}>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>

    <div id="heading">
		{% block heading %}{% endblock %}
	</div>
		<div class="container-fluid">
			<div class="rectangle">

			<div class="logo">
				<a href="/users/login">
				<img src="{% static "img/logo.png" %}" class="center">
				</a>
			</div>
		        {% block content %}{% endblock %}
		    </div>
		</div>
        <!--
        <div id="footer">
            <ul>
                <li><a href="/terms">terms</a></li>
                <li><a href="/jobs">jobs</a></li>
                <li><a href="/contact">contact us</a></li>
            </ul>
      </div>
      -->
  </body>
</html>

users/templates/coming_soon.html
{% extends "base.html" %}

{% load staticfiles %}

{% block heading %}

{% endblock %}

{% block content %}
	<div id="center_text">
		<img src="{% static "img/notyetavail.png" %}" class="center" width=300px>
	</div>
	
{% endblock %}

users/templates/error.html
{% extends "base.html" %}

{% load staticfiles %}

{% block heading %}

{% endblock %}

{% block content %}
	<div id="center_text">
		<h2>We're sorry, but there was an error creating your account. Please try again.</h2>
	</div>
	
{% endblock %}

users/templates/faq.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}

	<div class="login-form-wrapper">

		<b>Q: What is Over Easy?</b><br>
		A: Over Easy makes and delivers a delicious breakfast straight to your door in a selected 20-minute window. We understand that you want breakfast but that you don't have the time to get one in the morning. Now you can get that extra sleep you've always wanted <em>and</em> a complete breakfast.<br><br>

		<b>Q: What are your hours of operation?</b><br>
		A: Our first delivery window opens at 7:30am and our final delivery window ends at 10:10am.<br><br>

		<b>Q: Where does Over Easy get its ingredients?</b><br>
		A: It is our mission to create our dishes with farm fresh, seasonal, and local ingredients.<br><br>

		<b>Q: Where do you get your juices?</b><br>
		A: We get our juices from Cold Off the Press. Each one contains over 3 pounds of produce. Try them! They're amazing.<br><br>

		<b>Q: Is there a delivery fee?</b><br>
		A: Nope!<br><br>

		<b>Q: Is there a tip?</b><br>
		A: No delivery fee, no tip, no problem! We will simply drop off your breakfast in the morning.<br><br>

		<b>Q: How is payment accepted?</b><br>
		A: We accept credit and debit cards through Stripe, a highly secured third-party system.<br><br>

		<b>Q: Do you deliver coffee, or nah?</b><br>
		A: Hell yeah we do!<br><br>

		<b>Q: What if a delivery is late?</b><br>
		A: We guarantee your breakfast will arrive in the selected 20-minute time window. If we're late, then your breakfast is on us.<br><br>

		<b>Q: Who do I contact if I have a question about my order?</b><br>
		A: Email <a href="mailto:help@overeasyapp.com?Subject=My%20Order" target="_top">help@overeasyapp.com</a>. A real person will respond promptly.<br><br>

		<b>Q: Who took that awesome photo on your home page?</b><br>
		A: Thanks, Joann! <a href="http://instagram.com/sliceofpai">@sliceofpai</a><br><br>

	</div>

{% endblock %}

users/templates/homemenu.html
{% extends "staticpagebase.html" %}

{% load staticfiles %}

{% block content %}
	<a href="/">
	<img src="{% static "img/menu.png"%}" height="618" width="918" style="  pointer-events:none;" class="center">
	</a>	
{% endblock %}

users/templates/login.html
{% extends "base.html" %}

{% load staticfiles %}

{% block heading %}

{% endblock %}

{% block content %}
	<div id="center_text">
		<img src="{% static "img/text.png" %}" class="center" width="280px">
	</div>

	<div class="login-form-wrapper">

	<form method="post" action="login">
		{% csrf_token %}

			<div id="error-on-login">
				{{ error }}
			</div>

			<div class="form-group">
				<!--<label for="exampleInputEmail1">Email address</label>-->
				<input type="email" class="form-control" id="username" name="username" placeholder="Email">
			</div>


			  <div class="form-group">
			    <!--<label for="exampleInputPassword1">Password</label>-->
			    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
			  </div>


		<button type="submit" class="btn btn-default" style="width:49%;"><b>Sign In</b></button>

		<a href="/users/register"><input class="btn btn-default" style="width:49%; color:#000000; font-weight: bold; background-color:#FF9000;" value="Sign Up"></a>
	</form>
	
	</div>
	
	<br>

	<div id="box-footer">
			
		<ul>
			<!--<li><a href="/users/about"><b>About</b></a></li>-->
			<!--<li>&emsp; &emsp; &emsp; &emsp;</li>-->
			<li><a href="/users/faq"><b>FAQ</b></a></li>
			<li>&emsp; &emsp; &emsp; &emsp;</li>
			<li><a href="/users/homemenu"><b>Menu</b></a></li>
		</ul>			
	</div>

{% endblock %}

users/templates/reg-base.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/overeasy.css' %}">
<link href='http://fonts.googleapis.com/css?family=Oswald|Abel' rel='stylesheet' type='text/css'>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Over Easy</title>

    <!-- Bootstrap -->

    <title>{% block title %}Over Easy{% endblock %}</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
        <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-56248193-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>
  <body background={% static "img/overeasy-background.jpeg" %}>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>

    <div id="heading">
		{% block heading %}{% endblock %}
	</div>
		<div class="container-fluid">
			<div class="reg-rectangle">

			<div class="logo">
				<a href="/users/login">
				<img src="{% static "img/logo.png" %}" class="center">
				</a>
			</div>
		        {% block content %}{% endblock %}
		    </div>
		</div>
        <!--
        <div id="footer">
            <ul>
                <li><a href="/terms">terms</a></li>
                <li><a href="/jobs">jobs</a></li>
                <li><a href="/contact">contact us</a></li>
            </ul>
      </div>
      -->
  </body>
</html>

users/templates/register.html
{% extends "reg-base.html" %}

{% load staticfiles %}

{% block content %}

	<div class="login-form-wrapper">

	<div class="center_text">
		<img src="{% static "img/signuptoday.png" %}" class="center" width="280px">
	</div>
	<hr>

		<form method="post" action="process_new_user">
			{% csrf_token %}

			{% for error in nom_errors %}
			<div id="error-on-login">
			{{ error }}
			</div>
			{% endfor %}

			<div class="form-group">
				<input type="text" class="form-control" id="first" name="first" placeholder="First name">
			</div>
			<div class="form-group">
				<input type="text" class="form-control" id="last" name="last" placeholder="Last name">
			</div>

			{% for error in num_errors %}
			<div id="error-on-login">
			{{ error }}
			</div>
			{% endfor %}

			<div class="form-group">
			    <input type="text" class="form-control" id="phone" name="phone" placeholder="Phone">
			</div>

			<hr>
	
			{% for error in un_errors %}
			<div id="error-on-login">
			{{ error }}
			</div>
			{% endfor %}

			<div class="form-group">
			    <input type="email" class="form-control" id="username" name="username" placeholder="Email">
			</div>

			{% for error in pw_errors %}
			<div id="error-on-login">
			{{ error }}
			</div>
			{% endfor %}

			<div class="form-group">
			    <input type="password" class="form-control" id="password1" name="password1" placeholder="Password">
			</div>
			<div class="form-group">
			    <input type="password" class="form-control" id="password2" name="password2" placeholder="Re-type password">
			</div>

			<hr>

			{% for error in addr_errors %}
			<div id="error-on-login">
			{{ error }}
			</div>
			{% endfor %}

			<div class="form-group">
			    <input type="text" class="form-control" id="address1" name="address1" placeholder="Address">
			</div>
			<div class="form-group">
			    <input type="text" class="form-control" id="address2" name="address2" placeholder="Apt #, Suite, etc.">
			</div>
			<div class="form-group">
			    <input type="text" class="form-control" id="city" name="city" placeholder="City">
			</div>

			<select class="form-control" id="id_state" name="state" placeholder="State">
			{% for state in states %}
			<option value="{{ state }}" name="state">{{ state }}</option>
			{% endfor %}

			</select><br>

			<button type="submit" class="btn btn-default" style="width:100%; color:#000000; background-color:#FF9000;"><b>Submit</b></button>
		</form>

		<div id="home-page-footer">
			
			<ul>
				<li> </li>
				<!--<li><a href="about"><b>About</b></a></li>
				<li><a href="terms"><b>Terms</b></a></li>-->
			</ul>
			
		</div>


	</div>
{% endblock %}

users/templates/staticpagebase.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/overeasy.css' %}">
<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Over Easy</title>

    <!-- Bootstrap -->

    <title>{% block title %}Over Easy{% endblock %}</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
        <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-56248193-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>
  <body background={% static "img/overeasy-background.jpeg" %}>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>

    <div id="heading">
		{% block heading %}{% endblock %}
	</div>
		<div class="container-fluid">
			<div id="menurectangle">

		        {% block content %}{% endblock %}
		    </div>
		</div>
        <!--
        <div id="footer">
            <ul>
                <li><a href="/terms">terms</a></li>
                <li><a href="/jobs">jobs</a></li>
                <li><a href="/contact">contact us</a></li>
            </ul>
      </div>
      -->
  </body>
</html>

users/templates/welcome.html
{% extends "base.html" %}

{% block heading %}
	<h1>Welcome to Dormserv</h1>
{% endblock %}